# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.7 on 2026-07-10 18:07

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("django_qms", "0001_initial"),
        ("django_qms", "0002_alter_productrepresentation_unique_together_and_more"),
        ("django_qms", "0003_alter_storage_storage_manager"),
        ("django_qms", "0004_rename_salechannel_channel_alter_channel_options_and_more"),
        ("django_qms", "0005_alter_storage_storage_manager"),
        ("django_qms", "0006_alter_productrepresentation_sku_and_more"),
        ("django_qms", "0007_pointintime_proces_status"),
        ("django_qms", "0008_rename_pitquantity_zulupitquantity_and_more"),
        ("django_qms", "0009_alter_zulustorage_channel"),
        ("django_qms", "0010_xraypointintime_xrayproductrepresentation_and_more"),
        ("django_qms", "0011_xraystoragelink_delete_xrayquantity"),
        ("django_qms", "0012_warehouse"),
        ("django_qms", "0013_warehouse_is_active_idx"),
        ("django_qms", "0014_rename_django_qms__is_acti_idx_django_qms__is_acti_f5ea16_idx"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ZuluPointInTime",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pit", models.DateTimeField()),
                (
                    "proces_status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("canceled", "Canceled"),
                            ("error", "Error"),
                        ],
                        default="waiting",
                        max_length=12,
                    ),
                ),
            ],
            options={
                "verbose_name": "[Zulu] Point In Time",
                "verbose_name_plural": "[Zulu] Points In Time",
                "db_table": "django_qms_zulu_pit",
                "ordering": ["-pit"],
                "get_latest_by": "pit",
            },
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idx", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=128)),
                ("stock_weight", models.IntegerField(default=0)),
                (
                    "qms_type",
                    models.CharField(
                        choices=[
                            ("ALPHA", "Alpha"),
                            ("BRAVO", "Bravo"),
                            ("CHARLIE", "Charlie"),
                            ("DELTA", "Delta"),
                            ("ECHO", "Echo"),
                            ("FOXTROT", "Foxtrot"),
                            ("GOLF", "Golf"),
                            ("HOTEL", "Hotel"),
                            ("INDIA", "India"),
                            ("JULIET", "Juliet"),
                            ("KILO", "Kilo"),
                            ("LIMA", "Lima"),
                            ("MIKE", "Mike"),
                            ("NOVEMBER", "November"),
                            ("OSCAR", "Oscar"),
                            ("PAPA", "Papa"),
                            ("QUEBEC", "Quebec"),
                            ("ROMEO", "Romeo"),
                            ("SIERRA", "Sierra"),
                            ("TANGO", "Tango"),
                            ("UNIFORM", "Uniform"),
                            ("VICTOR", "Victor"),
                            ("WHISKEY", "Whiskey"),
                            ("XRAY", "Xray"),
                            ("ZULU", "Zulu"),
                        ],
                        db_index=True,
                        default="ZULU",
                        max_length=8,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "channels",
                "ordering": ["idx"],
                "unique_together": {("idx",), ("name",)},
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=128, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "source_type",
                    models.CharField(
                        choices=[("manual", "Manual (CMS)"), ("integration", "Integration (CSV/API)")],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("channels", models.ManyToManyField(blank=True, related_name="warehouses", to="django_qms.channel")),
            ],
            options={
                "db_table": "django_qms_warehouse",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WarehouseStock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("sku", models.CharField(db_index=True, max_length=128)),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="stocks", to="django_qms.warehouse"
                    ),
                ),
            ],
            options={
                "db_table": "django_qms_warehousestock",
            },
        ),
        migrations.CreateModel(
            name="XrayPointInTime",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pit", models.DateTimeField()),
                (
                    "proces_status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("canceled", "Canceled"),
                            ("error", "Error"),
                        ],
                        default="waiting",
                        max_length=12,
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="xray_pits", to="django_qms.channel"
                    ),
                ),
            ],
            options={
                "verbose_name": "[XRay] Point In Time",
                "verbose_name_plural": "[XRay] Points In Time",
                "db_table": "django_qms_xray_pit",
                "ordering": ["-pit"],
                "get_latest_by": "pit",
            },
        ),
        migrations.CreateModel(
            name="XrayProductRepresentation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sku", models.CharField(max_length=128)),
            ],
            options={
                "verbose_name": "[XRay] Product representation",
                "verbose_name_plural": "[XRay] Products representations",
                "db_table": "django_qms_xray_productrepresentation",
                "ordering": ["sku"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("sku"), name="unique_qms_xray_product_sku"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="XrayStorage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=100)),
                (
                    "storage_manager",
                    models.CharField(choices=[("checkout", "Checkout"), ("csv", "CSV")], max_length=20),
                ),
                ("data_direction", models.CharField(choices=[("input", "Input"), ("output", "Output")], max_length=20)),
                ("additional_data", models.JSONField(blank=True, default=dict)),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="xray_storages",
                        to="django_qms.channel",
                        verbose_name="channel",
                    ),
                ),
            ],
            options={
                "verbose_name": "[XRay] Storage",
                "verbose_name_plural": "[XRay] Storages",
                "db_table": "django_qms_xray_storage",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="XrayQuantityByStorage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity_int", models.IntegerField(default=0)),
                (
                    "pit",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_qms.xraypointintime"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="django_qms.xrayproductrepresentation"
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xray_quantities_by_storage",
                        to="django_qms.xraystorage",
                    ),
                ),
            ],
            options={
                "verbose_name": "[XRay] Quantity by Storage",
                "verbose_name_plural": "[XRay] Quantities by Storage",
                "db_table": "django_qms_xray_quantitybystorage",
            },
        ),
        migrations.CreateModel(
            name="XrayStorageLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "storage_input",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xray_storage_links_input",
                        to="django_qms.xraystorage",
                    ),
                ),
                (
                    "storage_output",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xray_storage_links_output",
                        to="django_qms.xraystorage",
                    ),
                ),
            ],
            options={
                "verbose_name": "[XRay] Storage Link",
                "verbose_name_plural": "[XRay] Storage Links",
                "db_table": "django_qms_xray_storagelink",
            },
        ),
        migrations.CreateModel(
            name="ZuluProductRepresentation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sku", models.CharField(max_length=128)),
                (
                    "product_algo",
                    models.CharField(choices=[("equal", "Equal"), ("split", "Split")], default="split", max_length=10),
                ),
            ],
            options={
                "verbose_name": "[Zulu] product representation",
                "verbose_name_plural": "[Zulu] products representations",
                "db_table": "django_qms_zulu_productrepresentation",
                "ordering": ["sku"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("sku"), name="unique_qms_zulu_product_sku"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ZuluPitQuantityByChannel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity_available", models.IntegerField(default=0)),
                ("quantity_locked", models.IntegerField(default=0)),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="django_qms.channel"
                    ),
                ),
                (
                    "pit",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_qms.zulupointintime"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="django_qms.zuluproductrepresentation"
                    ),
                ),
            ],
            options={
                "verbose_name": "[Zulu] PIT quantity by channel",
                "verbose_name_plural": "[Zulu] PIT quantities by channel",
                "db_table": "django_qms_zulu_pitquantitybychannel",
            },
        ),
        migrations.CreateModel(
            name="ZuluPitQuantity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity_available", models.IntegerField(default=0)),
                ("quantity_locked", models.IntegerField(default=0)),
                (
                    "pit",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_qms.zulupointintime"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="django_qms.zuluproductrepresentation"
                    ),
                ),
            ],
            options={
                "verbose_name": "[Zulu] PIT quantity",
                "verbose_name_plural": "[Zulu] PIT quantities",
                "db_table": "django_qms_zulu_pitquantity",
            },
        ),
        migrations.CreateModel(
            name="ZuluStorage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=100)),
                (
                    "storage_manager",
                    models.CharField(choices=[("checkout", "Checkout"), ("csv", "CSV")], max_length=20),
                ),
                ("additional_data", models.JSONField(blank=True, default=dict)),
                ("backup_data", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zulu_storages",
                        to="django_qms.channel",
                        verbose_name="channel",
                    ),
                ),
            ],
            options={
                "verbose_name": "[Zulu] storage",
                "verbose_name_plural": "[Zulu] storages",
                "db_table": "django_qms_zulu_storage",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ZuluPitSetupQuantity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity_available", models.IntegerField(default=0)),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="django_qms.channel"
                    ),
                ),
                (
                    "pit",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_qms.zulupointintime"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="django_qms.zuluproductrepresentation"
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_qms.zulustorage"),
                ),
            ],
            options={
                "verbose_name": "[Zulu] PIT setup quantity",
                "verbose_name_plural": "[Zulu] PIT setup quantities",
                "db_table": "django_qms_zulu_pitsetupquantity",
            },
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(fields=["is_active"], name="django_qms__is_acti_f5ea16_idx"),
        ),
        migrations.AddConstraint(
            model_name="warehousestock",
            constraint=models.UniqueConstraint(fields=("warehouse", "sku"), name="warehousestock_warehouse_sku_unique"),
        ),
        migrations.AddConstraint(
            model_name="warehousestock",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)), name="warehousestock_quantity_non_negative"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="xraystorage",
            unique_together={("channel", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="xrayquantitybystorage",
            unique_together={("product", "pit", "storage")},
        ),
        migrations.AlterUniqueTogether(
            name="zulupitquantitybychannel",
            unique_together={("pit", "channel", "product")},
        ),
        migrations.AlterUniqueTogether(
            name="zulupitquantity",
            unique_together={("pit", "product")},
        ),
        migrations.AlterUniqueTogether(
            name="zulustorage",
            unique_together={("channel", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="zulupitsetupquantity",
            unique_together={("pit", "storage", "product")},
        ),
    ]
